name: deploy-client

on:
  #push bcoz on merging PR, it counts a push to main branch
  push:
    branches:
      - main
    paths:
      #run when sth indide client is changed
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # ubuntu-latest has docker preinstalled
      - run: cd client && docker build -t schuylerdare96/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - run: docker push schuylerdare96/client
      # installs doctl into github container
      - uses: digitalocean/action-doctl@v2
        # this returns a pre-client docktl env
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-project
      # restart deployment
      - run: kubectl rollout restart deployment client-depl
