name: tests-auth

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
  # jobs: opens a ubuntu VM
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm i && npm run test:ci
      # test:ci- imp
      
    
